// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.allisonsPracticeBot.subsystems;

import org.usfirst.frc692.allisonsPracticeBot.RobotMap;
import org.usfirst.frc692.allisonsPracticeBot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class caterpillar extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController caterpillarMotorTwo = RobotMap.caterpillarcaterpillarMotorTwo;
    SpeedController caterpillarMotorOne = RobotMap.caterpillarcaterpillarMotorOne;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void caterpillarIn() {
    	caterpillarMotorTwo.set(0.7);
    	caterpillarMotorOne.set(-0.7);
    	//caterpillar moving tote in 70%
    	//AO 2/27/15
    }
    
    public void caterpillarOut() {
    	caterpillarMotorTwo.set(-0.7);
    	caterpillarMotorOne.set(0.7);
    	//caterpillar moving tote out 70%
    }
    
    public void caterpillarStop() {
    	caterpillarMotorTwo.set(0.0);
    	caterpillarMotorOne.set(0.0);
    	//caterpillar stop
    	//AO 4/27/15
    }
    
    
}

