// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.allisonsPracticeBot.subsystems;

import org.usfirst.frc692.allisonsPracticeBot.RobotMap;
import org.usfirst.frc692.allisonsPracticeBot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class mecanumDriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeftMotor = RobotMap.mecanumDriveTrainfrontLeftMotor;
    SpeedController frontRightMotor = RobotMap.mecanumDriveTrainfrontRightMotor;
    SpeedController backLeftMotor = RobotMap.mecanumDriveTrainbackLeftMotor;
    SpeedController backRightMotor = RobotMap.mecanumDriveTrainbackRightMotor;
    RobotDrive mecanumDriveTrain = RobotMap.mecanumDriveTrainmecanumDriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void moveForward () {
    	mecanumDriveTrain.mecanumDrive_Cartesian(0.0, 1.0, 0.0, 0.0);
    	//robot moves forward 
    	//AO 4/23/15
    }
    
    public void moveBackward () {
    	mecanumDriveTrain.mecanumDrive_Cartesian(0.0, -1.0, 0.0, 0.0);
    	//robot moves backward
    	//AO 4/23/15
    }
    
    public void moveRight () {
    	mecanumDriveTrain.mecanumDrive_Cartesian(1.0, 0.0, 0.0, 0.0);
    	//robot moves right
    	//AO 4/23/15
    }
    
    public void moveLeft () {
    	mecanumDriveTrain.mecanumDrive_Cartesian(-1.0, 0.0, 0.0, 0.0);
    	//robot moves left
    	//AO 4/23/15
    }
}

