// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.allisonsPracticeBot;

import org.usfirst.frc692.allisonsPracticeBot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick operatorOne;
    public Joystick operatorTwo;
    public Joystick driver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driver = new Joystick(2);
        
        operatorTwo = new Joystick(1);
        
        operatorOne = new Joystick(0);
        

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("driveFoward", new driveFoward());

        SmartDashboard.putData("driveBackward", new driveBackward());

        SmartDashboard.putData("driveLeft", new driveLeft());

        SmartDashboard.putData("driveRight", new driveRight());

        SmartDashboard.putData("driveJoystickValue", new driveJoystickValue());

        SmartDashboard.putData("caterpillarIn", new caterpillarIn());

        SmartDashboard.putData("caterpillarOut", new caterpillarOut());

        SmartDashboard.putData("caterpillarJoystickValue", new caterpillarJoystickValue());

        SmartDashboard.putData("gatherIn", new gatherIn());

        SmartDashboard.putData("gatherOut", new gatherOut());

        SmartDashboard.putData("GatherJoystickValue", new GatherJoystickValue());

        SmartDashboard.putData("elevatorDown", new elevatorDown());

        SmartDashboard.putData("ElevatorUp", new ElevatorUp());

        SmartDashboard.putData("elevatorJoystickValue", new elevatorJoystickValue());

        SmartDashboard.putData("flapperIn", new flapperIn());

        SmartDashboard.putData("flapperOut", new flapperOut());

        SmartDashboard.putData("driveTurnLeft", new driveTurnLeft());

        SmartDashboard.putData("driveTurnRight", new driveTurnRight());

        SmartDashboard.putData("gatherStop", new gatherStop());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getoperatorOne() {
        return operatorOne;
    }

    public Joystick getoperatorTwo() {
        return operatorTwo;
    }

    public Joystick getdriver() {
        return driver;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

